#!/usr/bin/env bash

clear
./gradlew assembleDebug
/Users/tmendici/Library/Android/sdk/platform-tools/adb install -r app/build/outputs/apk/app-debug.apk
/Users/tmendici/Library/Android/sdk/platform-tools/adb shell am start -n eu.neosurance.app/eu.neosurance.app.DemoActivity
./log
